spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_APPLICATION_CLIENT_ID}
            clientSecret: ${GITHUB_APPLICATION_CLIENT_SECRET}